server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
    }
}
